import apiClient from './client';
import { exerciseApi } from './exercise.api';

// ============================================================================
// TYPES
// ============================================================================

export interface GenerateWorkoutInput {
    goal: string;
    duration: number; // minutes
    equipment: string[];
    experienceLevel: string;
    injuries?: string;
    preferences?: string;
}

export interface GeneratedExercise {
    exerciseId: number;
    exercise: {
        id: number;
        name: string;
        targetMuscle: string;
        equipment: string;
        gifUrl?: string; // For icon/preview
    };
    sets: number;
    reps: string; // e.g., "10-12" or "60s"
    rest: number; // seconds
    notes?: string;
}

export interface GeneratedWorkout {
    workoutName: string;
    description: string;
    warmup: GeneratedExercise[];
    main: GeneratedExercise[];
    cooldown: GeneratedExercise[];
}

interface RawGeneratedExercise {
    exerciseId: number;
    sets: number;
    reps: string;
    rest: number;
    notes?: string;
}

interface RawGeneratedWorkout {
    workoutName: string;
    description: string;
    warmup?: RawGeneratedExercise[];
    main?: RawGeneratedExercise[];
    cooldown?: RawGeneratedExercise[];
}

// ============================================================================
// API FUNCTIONS
// ============================================================================

export const aiApi = {
    /**
     * Generate a workout using AI
     */
    generateWorkout: async (input: GenerateWorkoutInput): Promise<GeneratedWorkout> => {
        const response = await apiClient.post<{ success: boolean; data: RawGeneratedWorkout }>(
            '/routines/generate',
            input
        );

        const rawWorkout = response.data.data;
        const allExerciseIds = Array.from(new Set([
            ...(rawWorkout.warmup || []).map(item => Number(item.exerciseId)),
            ...(rawWorkout.main || []).map(item => Number(item.exerciseId)),
            ...(rawWorkout.cooldown || []).map(item => Number(item.exerciseId)),
        ].filter((id) => Number.isFinite(id) && id > 0)));

        const lookup = new Map<number, { id: number; name: string; targetMuscle: string; equipment: string; gifUrl?: string }>();
        const results = await Promise.allSettled(
            allExerciseIds.map((id) => exerciseApi.getExerciseById(id))
        );

        results.forEach((result, index) => {
            if (result.status !== 'fulfilled') return;
            const exercise = result.value;
            lookup.set(allExerciseIds[index], {
                id: Number(exercise.id),
                name: exercise.name || `Exercise ${allExerciseIds[index]}`,
                targetMuscle: exercise.muscleGroup || 'General',
                equipment: exercise.equipment || 'Unknown',
                gifUrl: exercise.thumbnailUrl || exercise.videoUrl,
            });
        });

        const enrichSection = (section?: RawGeneratedExercise[]): GeneratedExercise[] =>
            (section || []).map((item) => {
                const exercise = lookup.get(Number(item.exerciseId));
                return {
                    exerciseId: Number(item.exerciseId),
                    sets: Number(item.sets || 0),
                    reps: String(item.reps || ''),
                    rest: Number(item.rest || 0),
                    notes: item.notes,
                    exercise: exercise || {
                        id: Number(item.exerciseId),
                        name: `Exercise ${item.exerciseId}`,
                        targetMuscle: 'General',
                        equipment: 'Unknown',
                    },
                };
            });

        return {
            workoutName: rawWorkout.workoutName || 'AI Generated Workout',
            description: rawWorkout.description || 'Generated by AI',
            warmup: enrichSection(rawWorkout.warmup),
            main: enrichSection(rawWorkout.main),
            cooldown: enrichSection(rawWorkout.cooldown),
        };
    },
};
